// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

import 'menu/fake_data/item_menu_fake_data.dart';
import 'model/items_menu.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZrCwvXz2NvGyxfbWQOzrRhkwA_qvNAfQ',
    appId: '1:210566736827:web:bb6f151368f0f04704b29e',
    messagingSenderId: '210566736827',
    projectId: 'donuts-29c0b',
    authDomain: 'donuts-29c0b.firebaseapp.com',
    storageBucket: 'donuts-29c0b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKW6JoZ-_hRAxyEUOXXD_1H6ooErncw3E',
    appId: '1:210566736827:android:699399579b2eb78b04b29e',
    messagingSenderId: '210566736827',
    projectId: 'donuts-29c0b',
    storageBucket: 'donuts-29c0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_rzQkiAI1PjBP-4xTas2JIX1i0O84d3g',
    appId: '1:210566736827:ios:10e542c3102ed99a04b29e',
    messagingSenderId: '210566736827',
    projectId: 'donuts-29c0b',
    storageBucket: 'donuts-29c0b.appspot.com',
    iosClientId:
        '210566736827-ikav71j1laup037qvu9aefinltoieb0n.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_rzQkiAI1PjBP-4xTas2JIX1i0O84d3g',
    appId: '1:210566736827:ios:e3781b64bedfbad404b29e',
    messagingSenderId: '210566736827',
    projectId: 'donuts-29c0b',
    storageBucket: 'donuts-29c0b.appspot.com',
    iosClientId:
        '210566736827-r7v7itsjaeba5hqnb2acj9ib6fmmepn1.apps.googleusercontent.com',
    iosBundleId: 'com.example.app.RunnerTests',
  );
}
